### ISSUE TITLE
状态栏变成白色

### ISSUE THREAD

**Issue by Xdomino** [niorgai/StatusBarCompat#11]
调用translucentStatusBar(Activity activity, boolean hideStatusBarBackground)，后面的参数传true，在api
21上面，状态栏变成白色

**Comment by Xdomino** [comment]
传false的时候，界面顶部有一个按钮，结果被状态栏覆盖了，不能点击。

**Comment by niorgai** [comment]
能看下你的布局吗

**Comment by Xdomino** [comment]
主布局就是一个viewpager，然后viewpager里面有

不同的布局，发生问题的那个布局背景是一张图片，图片是延伸到了状态栏，

但是顶部的按钮也跟着上去了。

**Comment by Xdomino** [comment]
`<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.view.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</android.support.design.widget.CoordinatorLayout>`

**Comment by Xdomino** [comment]
就是引导页效果

**Comment by niorgai** [comment]
还是不是很明白..有图片吗

**Comment by Xdomino** [comment]
![qq 20160720100516](https://cloud.githubusercontent.com/assets/18133132/16973025/93b3e670-4e62-11e6-9375-770ffa65872e.png)
![qq 20160720101305](https://cloud.githubusercontent.com/assets/18133132/16973026/93b57af8-4e62-11e6-8f6e-46580d5d1b0f.png)

**Comment by Xdomino** [comment]
上面是主布局，下面是子布局，哪一个textview就是按钮

**Comment by Xdomino** [comment]
子布局那个paddingtop是我手动把它放下来了，不加就跑到状态栏

**Comment by niorgai** [comment]
你这样写跑到状态栏很正常啊...那个方法就是让布局延伸到状态栏的..

**Comment by Xdomino** [comment]
好吧
