### ISSUE TITLE
5.0以上版本  状态栏为白色

### ISSUE THREAD

**Issue by haoxikang** [niorgai/StatusBarCompat#12]
```
StatusBarCompat.translucentStatusBar(this, true); 设置了这个后 状态栏变成了纯白色 
```

**Comment by haoxikang** [comment]
![qq 20160809170113](https://cloud.githubusercontent.com/assets/13531074/17510807/ffbb8d5a-5e52-11e6-9a0d-2e1c2db1ec97.png)

**Comment by haoxikang** [comment]
![qq 20160809170308](https://cloud.githubusercontent.com/assets/13531074/17510837/2d91599e-5e53-11e6-8274-1f0ef593dfe6.png)
 设置成false就没这个问题 但是我不想要黑色的半透明背景

**Comment by niorgai** [comment]
我也发现了有bug...你想要的是什么效果呢..我打算弃用这个方法..

**Comment by haoxikang** [comment]
把这个 黑色背景去掉 就行了

**Comment by haoxikang** [comment]
不过在某些界面又没有这个问题

**Comment by niorgai** [comment]
我是测试过了..上次自己用的时候又不行了..可能跟我升级了版本有关  最近没有仔细看..

**Comment by haoxikang** [comment]
![qq 20160809170630](https://cloud.githubusercontent.com/assets/13531074/17511010/e94b5cd4-5e53-11e6-9414-0a253b1f7448.png)
在主界面又没问题 好奇怪

**Comment by niorgai** [comment]
系统版本是?

**Comment by haoxikang** [comment]
6.0.1

**Comment by Locke93** [comment]
@348476129 @niorgai  我也发现了一些问题，在切换是否使用透明时，我试着修改了一下，目前没有问题了（测试了4.4和6.0版本），请看https://github.com/lcokean/StatusBarDemo

**Comment by niorgai** [comment]
@lcokean 你好  我没有看到有什么改动啊...方便说一下吗

**Comment by Locke93** [comment]
@niorgai remove view 的时候mContentView.removeView(mChildView);改成了mDecorView.removeView(mChildView);        然后再其他一些地方加了 ViewCompat.requestApplyInsets(mChildView);

**Comment by Locke93** [comment]
@348476129 你试下用我改的那个，还会有问题吗？

**Comment by niorgai** [comment]
@lcokean 哦哦 看到了 不过这样还是会有问题..我再修复一下

**Comment by niorgai** [comment]
@348476129 release 1.2.0 版本已经修复这个问题
