### ISSUE TITLE
在6.0系统 设置了透明状态栏后android:windowSoftInputMode="adjustResize"属性失效

### ISSUE THREAD

**Issue by haoxikang** [niorgai/StatusBarCompat#13]
设置        StatusBarCompat.translucentStatusBar(this);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StatusBarCompat.translucentStatusBar(this, true);
        } 的时候 adjustResize 属性正常，设置后属性失效

**Comment by haoxikang** [comment]
= =滴滴滴滴 快看我的issue

**Comment by niorgai** [comment]
呃..最近网络屏蔽了Gmail没收到..我的7.0没问题啊

**Comment by LionsZhang** [comment]
华为手机系统5.1状态栏没有改变过来

**Comment by niorgai** [comment]
@LionsZhang 华为 Rom 问题,无能为力
