### ISSUE TITLE
在Nexus5X android 6.0.0下显示有问题

### ISSUE THREAD

**Issue by dingbuoyi** [niorgai/StatusBarCompat#15]
运行demo,第四个例子 Collapsing Toolbar,滑动到最顶端，Title显示不全

![image](https://cloud.githubusercontent.com/assets/476649/21629992/f0e6f7b8-d267-11e6-9438-68edac08d3ee.png)

**Comment by niorgai** [comment]
你好, 这是 Genymotion 吧. 我用原生模拟器没有复现喔.

**Comment by MAIMIHO** [comment]
作者你好, dingbuoyi 所说的这个问题确实存在, 在Sony Z2 Android6.0.1上面也存在这个问题.

**Comment by MAIMIHO** [comment]
@niorgai 下载代码后发现了另外一个问题. 
![image](https://cloud.githubusercontent.com/assets/18633356/21760462/489a5e14-d687-11e6-9a69-b5d9557028d7.png)
已经滑到最顶端.
![image](https://cloud.githubusercontent.com/assets/18633356/21760466/5ce3b546-d687-11e6-953b-86aa2a9a0c17.png)
![image](https://cloud.githubusercontent.com/assets/18633356/21760475/7350a186-d687-11e6-98f7-0f64417d4812.png)
另外状态栏出现了这种情况.

**Comment by niorgai** [comment]
呃.那可能还是有问题..但是发生的情况是同一个 Activity 多 tab 切换的时候偶现 (5.0 系统上) , 另外你上面发的图片中. demo 我为了对比把状态栏设置为黄色了, 但是界面顶上去了, 所以最后显示效果怪怪的.

**Comment by niorgai** [comment]
@dingbuoyi @MAIMIHO 我在本地做了一些尝试，因为我这边已经没问题了， 所以想问可以帮我测试一下吗？直接在 [fir.im](https://fir.im/StatusBarCompat) 下载 demo 即可。

1. 只需测试最后一个 tab。
2. 为了对比， 最后一个 tab 的状态栏设置为黄色了。

谢谢。

**Comment by MAIMIHO** [comment]
![device-2017-03-03-111947](https://cloud.githubusercontent.com/assets/18633356/23536935/88f7f6e2-0003-11e7-9ef2-04848b465b61.png)
![device-2017-03-03-111934](https://cloud.githubusercontent.com/assets/18633356/23536987/dc0101b2-0003-11e7-962f-59cdd83fa346.png)
![device-2017-03-03-111859](https://cloud.githubusercontent.com/assets/18633356/23536938/8e3499bc-0003-11e7-9713-71f2e479736f.png)
![device-2017-03-03-111909](https://cloud.githubusercontent.com/assets/18633356/23536936/892f9548-0003-11e7-8fb8-750e34652704.png)


测试结果如图, 5.1的华为上正常
6.0.1的Sony上不正常. 

我已经把布局边界显示出来截图了, 希望能帮助找到问题.

**Comment by niorgai** [comment]
@MAIMIHO 感谢帮忙，看来有些系统方法还是不好适配，可以看看新版本吗？我更新了 demo ，还是原来那个地址。

**Comment by MAIMIHO** [comment]
已解决, 赞
![image](https://cloud.githubusercontent.com/assets/18633356/23538126/e4ef78aa-000b-11e7-8726-1e35e8a06e3a.png)

**Comment by niorgai** [comment]
谢谢， 那算彻底解决了这个兼容问题。
