### ISSUE TITLE
引用失败

### ISSUE THREAD

**Issue by gaoyl87** [niorgai/StatusBarCompat#16]
lib的minSdk是15，我的项目minSdk是14，我的版本不能提高，要如何处理啊？

**Comment by niorgai** [comment]
呃。。这个最低版本没什么限制，我晚上发个新版改成14吧。14还是通用点。

**Comment by gaoyl87** [comment]
哪个版本的SDK要求低一点？我先用用试试看效果

**Comment by niorgai** [comment]
没有吧  我好像一开始就是15的  你可以把代码复制过去试试  就3个文件

**Comment by gaoyl87** [comment]
对哦。。。导入惯了忘记直接拷文件这招了

**Comment by niorgai** [comment]
你好，可以看看新版本能不能用，我顺便优化了下切换时候的动画。
