### ISSUE TITLE
设置window透明后，Activity进出默认动画被强制更改了

### ISSUE THREAD

**Issue by chenwulue** [niorgai/StatusBarCompat#17]
apptheme里增加`<item name="android:windowIsTranslucent">true</item>`后，动画有变

**Comment by niorgai** [comment]
不需要设置啊。。

**Comment by chenwulue** [comment]
是写其它功能要用到这个属性的时候 动画被改了，如果不用你的库，动画是不会被改的

**Comment by niorgai** [comment]
怎么重现呢？

**Comment by chenwulue** [comment]
你往你的demo加上<item name="android:windowIsTranslucent">true</item>就重现了吧

**Comment by niorgai** [comment]
并不能..我没看出什么不同的

**Comment by chenwulue** [comment]
oh no ...  只有4.4机型才会，我手头上的机型

**Comment by niorgai** [comment]
@chenwulue 好不容易找了一台4.4的。。还是没看出来问题在哪

**Comment by niorgai** [comment]
好像偶然重现了这个问题, 好像是 windowBackground 会影响系统动画. 不过我也没想到什么好方法...
