### ISSUE TITLE
andorid 7.0 没有变透明

### ISSUE THREAD

**Issue by tsm19911014** [niorgai/StatusBarCompat#19]

**Comment by niorgai** [comment]
...麻烦尽量完整点..比如机型?调用方法?最后的截图?

**Comment by tsm19911014** [comment]
我在FragmentActivity 里引用的

setContentView(R.layout.activity_home);
 mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                StatusBarCompat.translucentStatusBar(mActivity, true);
            }
        }, 500);

如果不用handler延时,就不会产生透明效果,但是如果用handler延时,效果就是完全透明的

**Comment by niorgai** [comment]
布局是怎样的呢? 
能不能看看更多方法呢? 或者完整的设置布局代码块?

**Comment by niorgai** [comment]
translucentStatusBar 的效果就是完全透明
