### ISSUE TITLE
透明状态栏在 21以上并不透明

### ISSUE THREAD

**Issue by wznshuai** [niorgai/StatusBarCompat#2]

**Comment by niorgai** [comment]
你好, 可以再详细说明一下吗

**Comment by wznshuai** [comment]
就是一个半透明的效果在上面，感觉怪怪的
![image](https://cloud.githubusercontent.com/assets/1897647/14270855/ddd16c82-fb24-11e5-9884-331cefa03772.png)
还有一个问题，发现在同一个Activity中不同fragment全屏和状态栏着色之间切换的时候会有高度偏移的问题，尝试解决了下但是发现在三星机器上还有同样问题，nexus5到是没问题
![image](https://cloud.githubusercontent.com/assets/1897647/14270914/875ee3b0-fb25-11e5-860d-0b9c1fe826e4.png)
第一张图会发现下面的menu会有底部加了paddingbottom的效果

![image](https://cloud.githubusercontent.com/assets/1897647/14270919/93378fac-fb25-11e5-80d3-c1a25fecb2e3.png)

这张图会出现有一部分在屏幕下半部分的效果

**Comment by niorgai** [comment]
这很正常啊..系统就会带上这个半透明的背景色

**Comment by niorgai** [comment]
@wznshuai 你好,我 release 了 v1.0.1, 添加了新方法:

```
//当SDK >= 21时, 是否需要隐藏状态栏的背景色(默认的黑色背景)
StatusBarCompat.translucentStatusBar(Activity activity, boolean hideStatusBarBackground);
```

不知道这个能不能解决你的需求

**Comment by wznshuai** [comment]
@niorgai HI  你好 我fork了StatusBarUtil 
https://github.com/wznshuai/StatusBarUtil 你可以运行下DEMO看下，我觉得可以满足我的需求了
点击Set Transparent按钮 里面有两个按钮分别是变幻为着色模式和沉浸模式

**Comment by niorgai** [comment]
@wznshuai 看了一下代码, 提醒一下切换沉浸模式后在 5.0 以上的系统需要让子 View 重新 Layout 一次, 这个我试过在 Fragment 切换的时候不重新 Layout 底部会有留白. 另外我觉得不需要添加 `FLAG_TRANSLUCENT_NAVIGATION` 这个 flag , 不然虚拟按键的机器兼容不好

**Comment by wznshuai** [comment]
@niorgai 对留白的问题就是需要设置一下ViewCompat.requestApplyInsets(VIEW);

**Comment by niorgai** [comment]
@wznshuai 赞

**Comment by wznshuai** [comment]
@niorgai 修改了一下5.0以上沉浸和着色的实现， 效果现在看起来很完美

**Comment by TopTime1** [comment]
你好我也遇到这个问题，在三星6.0.1上，怎么解决呢？

**Comment by niorgai** [comment]
@TopTime1 你好, 如果你指灰色条的话, 这是正常的. 想隐藏可以调用 `translucentStatusBar(this, true)` 方法
