### ISSUE TITLE
API 19 bug

### ISSUE THREAD

**Issue by woodnaonly** [niorgai/StatusBarCompat#21]
![4 4bug](https://cloud.githubusercontent.com/assets/11649184/24434296/48b082e4-1461-11e7-8c7d-db3d96895ef9.png)

**Comment by woodnaonly** [comment]
BaseActivity

>protected void onCreate( Bundle savedInstanceState)
 >{
>		super.onCreate(savedInstanceState);
>		setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
>		StatusBarCompat.setStatusBarColor(this, ContextCompat.getColor(this, R.color.colorAccent));
>	
>
>}

**Comment by niorgai** [comment]
you should call this method after `setContentView()`.

Get more information from README
