### ISSUE TITLE
关于transparent模式键盘不弹

### ISSUE THREAD

**Issue by wangshaolei** [niorgai/StatusBarCompat#22]
@niorgai 
关于transparent模式键盘不弹，作者有好的实践方案没有

**Comment by niorgai** [comment]
可以详细描述下吗? 不是很懂.
或者附上复现的代码

**Comment by wangshaolei** [comment]
@niorgai 不好意思 我的描述有问题~
假如我用transparent模式 图片全透到状态栏上， 配合adjustResize 不起作用，输入框不会跟随布局弹出。

**Comment by wangshaolei** [comment]
@niorgai 
我看了你们实现方式差不多。都有这个问题。
https://github.com/laobie/StatusBarUtil/issues/89

**Comment by niorgai** [comment]
还是不是很懂...能不能给个 demo 来看看呢?

**Comment by hadisi5216** [comment]
亲测有效https://stackoverflow.com/questions/7417123/android-how-to-adjust-layout-in-full-screen-mode-when-softkeyboard-is-visible/19494006#19494006

**Comment by cuibty** [comment]
确实有这个问题
StatusBarCompat.translucentStatusBar(this, true);

EditText 键盘会遮住布局，不会往上顶。

**Comment by cuibty** [comment]
https://github.com/madebycm/AndroidBug5497Workaround

亲测有效

**Comment by dahai2070** [comment]
如果这个问题，经常有人遇到的话，可否添加到介绍页面上去

**Comment by niorgai** [comment]
@dahai2070 应该的
