### ISSUE TITLE
collapsingToolbar状态栏颜色混乱

### ISSUE THREAD

**Issue by erik915** [niorgai/StatusBarCompat#24]
collapsingToolbar 如果快速话动几次，状态栏的颜色就乱了，展开的时候状态变成了黄颜色， 折叠后状态栏变成和toolbar一样的蓝色

**Comment by niorgai** [comment]
之前做的时候因为不想再弄一个 Animator 对象出来..所以偷懒了..果然还是不够严谨..已修复,谢谢.
