### ISSUE TITLE
混合调用的bug

### ISSUE THREAD

**Issue by szhupeng** [niorgai/StatusBarCompat#26]
实例这种同一个activity，不同的fragment，当在一个fragment A中调用：
 @Override
    public void onHiddenChanged(boolean hidden) {
        super.onHiddenChanged(hidden);
        if (!hidden) {
            StatusBarCompat.setStatusBarColorForCollapsingToolbar(getActivity(), mAppBarLayout, mCollapsingToolbarLayout, mToolbar, Color.TRANSPARENT);
        }
    }
然后在另一个fragment B中调用：
  @Override
    public void onHiddenChanged(boolean hidden) {
        super.onHiddenChanged(hidden);
        if (!hidden) {
            StatusBarCompat.setStatusBarColor(getActivity(), getActivity().getResources().getColor(R.color.primary));
        }
    }
当点击底部tab显示fragment A后再点击底部tab显示fragment B后，状态栏的颜色并不是primary而是透明的。

**Comment by niorgai** [comment]
在我提供的  Demo 中, Tab 4就是你所说的 Tab A, Tab 1 就是你所说的 Tab B, 你可以先试一下 Demo 的切换有没有问题.

如果还是不对尽量附图再提供一下系统版本号.

**Comment by szhupeng** [comment]
不好意思，是我这边设置错了
