### ISSUE TITLE
statusBar 无法显示阴影

### ISSUE THREAD

**Issue by DemoJameson** [niorgai/StatusBarCompat#28]
运行示例代码，小米 4 MIUI 8.7.10.26 在 Translucent 界面点击 Toogle 按钮后顶部状态栏没有任何变化。
朋友的小米手机也有同样的问题，机型系统未知。

**Comment by niorgai** [comment]
Android 版本是?

**Comment by niorgai** [comment]
最好附上能够复现的代码和手机型号

**Comment by niorgai** [comment]
I'm going to close this issue, if this issue is still present, please feel free to reopen it.
