### ISSUE TITLE
引用databing 部分手机 标题栏被状态栏遮挡了一个状态栏高度

### ISSUE THREAD

**Issue by Voidruiyi** [niorgai/StatusBarCompat#30]
如题

**Comment by niorgai** [comment]
理论上来说 dataBingding 不会影响, 最好附上能够复现的代码和手机型号

**Comment by Voidruiyi** [comment]
手机型号是4.4 oppor7s   4.4 锤子，代码databingding常规写法， 侵入栏设置   StatusBarCompat.setStatusBarColor(this, getResources().getColor(R.color.color_bg_titlelay));
当然在  setContentView() 后

**Comment by niorgai** [comment]
4.4 上用模拟器无法重现..

**Comment by yingjinWong** [comment]
没有引用也出现这个问题，android4.4

**Comment by niorgai** [comment]
@yingjinWong 应该是用法不对  最好有机型和代码方便复现

**Comment by myliuyx** [comment]
我们也遇到了这样的问题， 在安卓4.4.4 的手机上 
  StatusBarCompat.setStatusBarColor(activity, color);

设置了没有效果 导航栏跑到通知栏了。

**Comment by niorgai** [comment]
最好能提供在模拟器上能够复现的代码 @myliuyx

**Comment by niorgai** [comment]
I'm going to close this issue, if this issue is still present, please feel free to reopen it.
