### ISSUE TITLE
在android8.1.0上面部分机型不好用,

### ISSUE THREAD

**Issue by tsm19911014** [niorgai/StatusBarCompat#34]
小米的mix2 上面测试不好用,最新发现的,求大神指点

**Comment by niorgai** [comment]
信息再具体点?哪个方法不好用?那个方法失效了? 最好提供布局和代码以供复现, 或者运行 Demo.
我在 Pixel 2 XL 下测试是没问题的, 也是8.1.0

**Comment by tsm19911014** [comment]
这个我已经找到原因了,是因为没有适配大屏幕宽高比的原因

**Comment by tsm19911014** [comment]
加上       <meta-data android:name="android.max_aspect" android:value="2.1" />  大屏幕宽高比就好了, 我也奇怪,在调试的时候都没有报错,但是就是没有沉浸式效果

**Comment by niorgai** [comment]
呃..说明一下? 或者看看样式怎么了...这样以后我遇到也知道问题

**Comment by tsm19911014** [comment]
给我个邮箱吧,我给你发邮件,这样子说不清楚

**Comment by niorgai** [comment]
@tsm19911014 jianqiu.sysu@gmail.com THX.
