### ISSUE TITLE
清单文件中的application属性冲突

### ISSUE THREAD

**Issue by VinPin** [niorgai/StatusBarCompat#36]
能不能把清单文件中的application的两个属性android:allowBackup="true"和android:supportsRtl="true"去掉，与我项目中的合并冲突了。
`Error: 	Attribute application@allowBackup value=(false) from AndroidManifest.xml:20:9-36 	
is also present at [com.github.niorgai:StatusBarCompat:2.1.4] AndroidManifest.xml:12:9-35 value=(true). 	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at
AndroidManifest.xml:18:5-412:19 to override.`

**Comment by niorgai** [comment]
你可以先试试 `tools:replace="android:allowBackup`
