### ISSUE TITLE
有改变状态栏的文字颜色的功能吗

### ISSUE THREAD

**Issue by gyb3320** [niorgai/StatusBarCompat#38]
我现在的app标题栏是白色的，状态栏的文字看不到了，需要设置状态的文字颜色为黑色，如何实现？

**Comment by iceuncle** [comment]
同问，怎么样才能动态改变状态的文字的颜色呢？黑白切换就行。

**Comment by niorgai** [comment]
目前没有, 这也是6.0以上才有的功能, 建议换成灰色, 可参考微博国际版
