### ISSUE TITLE
希望能够给出状态栏黑色字体的方法

### ISSUE THREAD

**Issue by yizems** [niorgai/StatusBarCompat#39]
我最近在做一个需求,状态栏黑色字体(只是android6以上即可),但是我设置了后,就无法侵入状态栏了

**Comment by yizems** [comment]
fix by [Pull Requst](https://github.com/niorgai/StatusBarCompat/pull/40)

**Comment by niorgai** [comment]
还是 fork 后自己维护一个针对自己项目的好一些, 我已经在 PR 里面回复了, 谢谢
