### ISSUE TITLE
No changeToLightStatusBar and cancelLightStatusBar methods when use (Before AndroidX)

### ISSUE THREAD

**Issue by onecoders** [niorgai/StatusBarCompat#46]
add library
// Before AndroidX
	compile ('com.github.niorgai:StatusBarCompat:2.1.4', {
	    exclude group: 'com.android.support'
	})
changeToLightStatusBar and cancelLightStatusBar methods not found in StatusBarCompat

**Comment by niorgai** [comment]
Right, it is new feature. Just copy from source code and it should work.
