### ISSUE TITLE
大佬有问题啊

### ISSUE THREAD

**Issue by yudengwei** [niorgai/StatusBarCompat#47]
StatusBarCompat.setStatusBarColorForCollapsingToolbar用这个方法的时候，会报
android.widget.FrameLayout$LayoutParams cannot be cast to android.support.design.widget.CollapsingToolbarLayout$LayoutParams 强制转换的错误，实在是不懂啊

**Comment by yudengwei** [comment]
不好意思，是我自己蠢了，没问题的，对不起

**Comment by niorgai** [comment]
...看来你改了一点布局..复制下代码去改应该就可以了..
