### ISSUE TITLE
为什么间距变小了，要重叠了？

### ISSUE THREAD

**Issue by mxdlsm** [niorgai/StatusBarCompat#48]
![wechatimg28](https://user-images.githubusercontent.com/22886455/53729243-b34ede00-3eaf-11e9-91bf-9ab0a0b7219b.jpeg)

**Comment by niorgai** [comment]
附上代码和原图比较好理解.

**Comment by mxdlsm** [comment]
<img width="811" alt="2019-03-05 09 53 46" src="https://user-images.githubusercontent.com/22886455/53775227-9c9a9c80-3f2c-11e9-9123-68fc75b30e1b.png">

**Comment by niorgai** [comment]
还是没懂..你这个描述我看不懂你想要什么想过..

`translucentStatusBar` 就是把布局从状态栏开始往下排

**Comment by niorgai** [comment]
太久没反馈我先关闭了.还有问题随时打开
