### ISSUE TITLE
使用gradle导包有问题

### ISSUE THREAD

**Issue by mawenge** [niorgai/StatusBarCompat#9]
Error:(25, 13) Failed to resolve: com.github.niorgai:StatusBarCompat:1.1.0

<a href="openFile:D:/StudioProjects/RadioButtonGroup/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by niorgai** [comment]
有没有在你项目的 `build.gradle` 中加上

```
  allprojects {
      repositories {
          ...
          maven { url "https://jitpack.io" }
      }
  }
```

**Comment by mawenge** [comment]
哦哦，原来是这样，非常感谢

**Comment by crykid** [comment]
我也碰到了这个问题，上面那句我是添加了的
